name: CDK Diff

on:
  pull_request:

jobs:
  cdk-diff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install test app dependencies
        run: npm install
        working-directory: test-cdk-app

      - name: Run CDK Diff Report
        uses: dzon337/cdk-diff-visualizer@v1.1.0
        with:
          working-directory: test-cdk-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}